<?php

namespace App\Models;

use App\Observers\MainCategoryObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\SubCategory;

class MainCategory extends Model
{
    use HasFactory;
    protected $table = 'main_categories';
    protected $fillable = [
        'id', 'translation_lang', 'translate_of', 'name', 'slug', 'photo', 'active', 'created_at',	'updated_at'
    ];

    public function scopeActive($query){
        return $query ->where('active', 1);
    }

    public function getPhotoAttribute($val)
    {
        return ($val !== null) ? asset('assets/' . $val) : "";

    }

    public function scopeSelection($query)
    {

        return $query ->select('id', 'translation_lang', 'name', 'slug', 'photo', 'active', 'translate_of');
    }

    public function getActive()
    {
        return $this -> active == 1 ? 'مفعل' : 'غبر مفعل';
    }

    //get all translation category
    public function categories()
    {
        return $this->hasMany(self::class, 'translate_of');
    }

    public function subCategories()
    {
        return $this -> hasMany(SubCategory::class, 'category_id', 'id');
    }

    public function vendors(){
        return $this -> hasMany('App\Models\Vendor', 'category_id', 'id');
    }
    public function products(){
        return $this -> hasMany('App\Models\Product', 'category_id', 'id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        MainCategory::observe(MainCategoryObserver::class);
    }

    public function scopeDefaultCategory($query)
    {
        return $query -> where('translate_of',0);
    }
}
